# -*- coding: utf-8 -*-
"""E-scooter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15FNDSeQNS-Doxr_eUMQF09HQeXU7elmh
"""


class Escooter_PowerConsumptionCalculator:
    def __init__(self, Cr=0.001, Cd=0.7, A=2.5, rho=1.29, g=9.81):
        self.Cr = Cr  # 滚动阻力系数
        self.Cd = Cd  # 阻力系数
        self.A = A  # 正面积
        self.rho = rho  # 空气密度
        self.g = g  # 重力加速度

    def calculate(self, v, m, s):
        """
        v -- 速度 (Km/s)
        m -- 质量 (kg)
        s -- 斜坡倾斜度
        """
        return (self.Cr * m * self.g + 0.5 * self.Cd * self.rho * self.A * v * v) # W
